### ISSUE TITLE
Could you change the lib directory?

### ISSUE THREAD

**Issue by zhgeaits** [nhachicha/android-native-dependencies#7]
Hi, your android-native-dependencies is great. Thanks for sharing.
I have found that in copyToTarget you use the directory:
"$project.projectDir"+File.separator+
"src"+File.separator+"main"+File.separator+
"jniLibs"+File.separator+"$architecture"
However, if i change the android sourceset, that is not right, you may use jniLibs.srcDirs which is better.

**Comment by nhachicha** [comment]
Hi @zhgeaits 
Spot on! It'd be awesome if you could send a PR.
Cheers,

**Comment by zhgeaits** [comment]
Sorry, i don't understand what is "PR"?
What I mean is that I change android sourceset like this:
sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }
However, your resolveNativeDependencies task just copy *.so into "src/main/jinLibs".

**Comment by nhachicha** [comment]
Fixed in [0.1.2](https://github.com/nhachicha/android-native-dependencies/tree/0.1.2) release

Cheers,
