### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by xialin** [nhachicha/android-native-dependencies#8]
Will you add support for arm64-v8a?

**Comment by nhachicha** [comment]
Hi @xialin 
Yep probably this weekend. I already have a [PR](https://github.com/nhachicha/android-native-dependencies/pull/6) that handles this abi. 

Cheers,

**Comment by nhachicha** [comment]
Fixed in [0.1.2](https://github.com/nhachicha/android-native-dependencies/tree/0.1.2)

Cheers,
